package foreign;
// Generated Mar 24, 2013 9:34:32 PM by Hibernate Tools 3.2.1.GA



/**
 * BookingProductData generated by hbm2java
 */
public class BookingProductData  implements java.io.Serializable {


     private Integer tid;
     private String pid;
     private String uid;
     private String dateOfBooking;
     private String status;
     private String deliveryAddress;
     private int noOfDaysOfDeliveryFromBooking;

    public BookingProductData() {
    }

    public BookingProductData(String pid, String uid, String dateOfBooking, String status, String deliveryAddress, int noOfDaysOfDeliveryFromBooking) {
       this.pid = pid;
       this.uid = uid;
       this.dateOfBooking = dateOfBooking;
       this.status = status;
       this.deliveryAddress = deliveryAddress;
       this.noOfDaysOfDeliveryFromBooking = noOfDaysOfDeliveryFromBooking;
    }
   
    public Integer getTid() {
        return this.tid;
    }
    
    public void setTid(Integer tid) {
        this.tid = tid;
    }
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    public String getDateOfBooking() {
        return this.dateOfBooking;
    }
    
    public void setDateOfBooking(String dateOfBooking) {
        this.dateOfBooking = dateOfBooking;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDeliveryAddress() {
        return this.deliveryAddress;
    }
    
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }
    public int getNoOfDaysOfDeliveryFromBooking() {
        return this.noOfDaysOfDeliveryFromBooking;
    }
    
    public void setNoOfDaysOfDeliveryFromBooking(int noOfDaysOfDeliveryFromBooking) {
        this.noOfDaysOfDeliveryFromBooking = noOfDaysOfDeliveryFromBooking;
    }




}


