package foreign;
// Generated Mar 24, 2013 9:34:32 PM by Hibernate Tools 3.2.1.GA



/**
 * DelivBoy generated by hbm2java
 */
public class DelivBoy  implements java.io.Serializable {


     private String dbid;
     private String psw;
     private String SAdminid;
     private String dname;
     private String location;
     private int lid;
     private String areaOfCoverage;
     private String phone;
     private int dailyDelvGoodsCapacity;

    public DelivBoy() {
    }

    public DelivBoy(String dbid, String psw, String SAdminid, String dname, String location, int lid, String areaOfCoverage, String phone, int dailyDelvGoodsCapacity) {
       this.dbid = dbid;
       this.psw = psw;
       this.SAdminid = SAdminid;
       this.dname = dname;
       this.location = location;
       this.lid = lid;
       this.areaOfCoverage = areaOfCoverage;
       this.phone = phone;
       this.dailyDelvGoodsCapacity = dailyDelvGoodsCapacity;
    }
   
    public String getDbid() {
        return this.dbid;
    }
    
    public void setDbid(String dbid) {
        this.dbid = dbid;
    }
    public String getPsw() {
        return this.psw;
    }
    
    public void setPsw(String psw) {
        this.psw = psw;
    }
    public String getSAdminid() {
        return this.SAdminid;
    }
    
    public void setSAdminid(String SAdminid) {
        this.SAdminid = SAdminid;
    }
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public int getLid() {
        return this.lid;
    }
    
    public void setLid(int lid) {
        this.lid = lid;
    }
    public String getAreaOfCoverage() {
        return this.areaOfCoverage;
    }
    
    public void setAreaOfCoverage(String areaOfCoverage) {
        this.areaOfCoverage = areaOfCoverage;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public int getDailyDelvGoodsCapacity() {
        return this.dailyDelvGoodsCapacity;
    }
    
    public void setDailyDelvGoodsCapacity(int dailyDelvGoodsCapacity) {
        this.dailyDelvGoodsCapacity = dailyDelvGoodsCapacity;
    }




}


