package foreign;
// Generated Mar 24, 2013 9:34:32 PM by Hibernate Tools 3.2.1.GA



/**
 * GoodsData generated by hbm2java
 */
public class GoodsData  implements java.io.Serializable {


     private Integer pid;
     private String productName;
     private int availableQuantity;
     private int unitPrice;
     private int cid;

    public GoodsData() {
    }

    public GoodsData(String productName, int availableQuantity, int unitPrice, int cid) {
       this.productName = productName;
       this.availableQuantity = availableQuantity;
       this.unitPrice = unitPrice;
       this.cid = cid;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public int getAvailableQuantity() {
        return this.availableQuantity;
    }
    
    public void setAvailableQuantity(int availableQuantity) {
        this.availableQuantity = availableQuantity;
    }
    public int getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(int unitPrice) {
        this.unitPrice = unitPrice;
    }
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }




}


