package foreign;
// Generated Mar 24, 2013 9:34:32 PM by Hibernate Tools 3.2.1.GA



/**
 * ImageUpdate generated by hbm2java
 */
public class ImageUpdate  implements java.io.Serializable {


     private Integer imageId;
     private String pid;
     private String imageTitle;
     private String imageUrl;

    public ImageUpdate() {
    }

    public ImageUpdate(String pid, String imageTitle, String imageUrl) {
       this.pid = pid;
       this.imageTitle = imageTitle;
       this.imageUrl = imageUrl;
    }
   
    public Integer getImageId() {
        return this.imageId;
    }
    
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public String getImageTitle() {
        return this.imageTitle;
    }
    
    public void setImageTitle(String imageTitle) {
        this.imageTitle = imageTitle;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }




}


