package foreign;
// Generated Mar 24, 2013 9:34:32 PM by Hibernate Tools 3.2.1.GA



/**
 * LocationData generated by hbm2java
 */
public class LocationData  implements java.io.Serializable {


     private Integer lid;
     private String locationName;

    public LocationData() {
    }

    public LocationData(String locationName) {
       this.locationName = locationName;
    }
   
    public Integer getLid() {
        return this.lid;
    }
    
    public void setLid(Integer lid) {
        this.lid = lid;
    }
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }




}


