package foreign;
// Generated Mar 24, 2013 9:34:32 PM by Hibernate Tools 3.2.1.GA



/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer SNo;
     private String tid;
     private String dbid;
     private String dateOfAllocation;
     private String dateOfDelivery;

    public Status() {
    }

    public Status(String tid, String dbid, String dateOfAllocation, String dateOfDelivery) {
       this.tid = tid;
       this.dbid = dbid;
       this.dateOfAllocation = dateOfAllocation;
       this.dateOfDelivery = dateOfDelivery;
    }
   
    public Integer getSNo() {
        return this.SNo;
    }
    
    public void setSNo(Integer SNo) {
        this.SNo = SNo;
    }
    public String getTid() {
        return this.tid;
    }
    
    public void setTid(String tid) {
        this.tid = tid;
    }
    public String getDbid() {
        return this.dbid;
    }
    
    public void setDbid(String dbid) {
        this.dbid = dbid;
    }
    public String getDateOfAllocation() {
        return this.dateOfAllocation;
    }
    
    public void setDateOfAllocation(String dateOfAllocation) {
        this.dateOfAllocation = dateOfAllocation;
    }
    public String getDateOfDelivery() {
        return this.dateOfDelivery;
    }
    
    public void setDateOfDelivery(String dateOfDelivery) {
        this.dateOfDelivery = dateOfDelivery;
    }




}


