package foreign;
// Generated Mar 24, 2013 9:34:32 PM by Hibernate Tools 3.2.1.GA



/**
 * Subadmin generated by hbm2java
 */
public class Subadmin  implements java.io.Serializable {


     private String SLoginid;
     private String name;
     private String password;
     private String address;
     private String branch;
     private String phno;

    public Subadmin() {
    }

    public Subadmin(String SLoginid, String name, String password, String address, String branch, String phno) {
       this.SLoginid = SLoginid;
       this.name = name;
       this.password = password;
       this.address = address;
       this.branch = branch;
       this.phno = phno;
    }
   
    public String getSLoginid() {
        return this.SLoginid;
    }
    
    public void setSLoginid(String SLoginid) {
        this.SLoginid = SLoginid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getPhno() {
        return this.phno;
    }
    
    public void setPhno(String phno) {
        this.phno = phno;
    }




}


