package foreign;
// Generated Mar 24, 2013 9:34:32 PM by Hibernate Tools 3.2.1.GA



/**
 * UserData generated by hbm2java
 */
public class UserData  implements java.io.Serializable {


     private String uid;
     private String UName;
     private String gender;
     private String address;
     private String phone;
     private String password;

    public UserData() {
    }

    public UserData(String uid, String UName, String gender, String address, String phone, String password) {
       this.uid = uid;
       this.UName = UName;
       this.gender = gender;
       this.address = address;
       this.phone = phone;
       this.password = password;
    }
   
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    public String getUName() {
        return this.UName;
    }
    
    public void setUName(String UName) {
        this.UName = UName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


