package foreign;
// Generated Mar 24, 2013 9:34:32 PM by Hibernate Tools 3.2.1.GA



/**
 * UserFeedback generated by hbm2java
 */
public class UserFeedback  implements java.io.Serializable {


     private String fid;
     private String uid;
     private String dbid;
     private String feedbackContent;
     private int feedbackStarNo;
     private String cdateoffeedback;
     private String feedbackstatus;

    public UserFeedback() {
    }

    public UserFeedback(String fid, String uid, String dbid, String feedbackContent, int feedbackStarNo, String cdateoffeedback, String feedbackstatus) {
       this.fid = fid;
       this.uid = uid;
       this.dbid = dbid;
       this.feedbackContent = feedbackContent;
       this.feedbackStarNo = feedbackStarNo;
       this.cdateoffeedback = cdateoffeedback;
       this.feedbackstatus = feedbackstatus;
    }
   
    public String getFid() {
        return this.fid;
    }
    
    public void setFid(String fid) {
        this.fid = fid;
    }
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    public String getDbid() {
        return this.dbid;
    }
    
    public void setDbid(String dbid) {
        this.dbid = dbid;
    }
    public String getFeedbackContent() {
        return this.feedbackContent;
    }
    
    public void setFeedbackContent(String feedbackContent) {
        this.feedbackContent = feedbackContent;
    }
    public int getFeedbackStarNo() {
        return this.feedbackStarNo;
    }
    
    public void setFeedbackStarNo(int feedbackStarNo) {
        this.feedbackStarNo = feedbackStarNo;
    }
    public String getCdateoffeedback() {
        return this.cdateoffeedback;
    }
    
    public void setCdateoffeedback(String cdateoffeedback) {
        this.cdateoffeedback = cdateoffeedback;
    }
    public String getFeedbackstatus() {
        return this.feedbackstatus;
    }
    
    public void setFeedbackstatus(String feedbackstatus) {
        this.feedbackstatus = feedbackstatus;
    }




}


